In [1]:
import numpy as np

In [2]:
l1=[[11,22,33,44],[22,33,55,123]]
arr=np.array(l1,np.int64)
arr

array([[ 11,  22,  33,  44],
       [ 22,  33,  55, 123]], dtype=int64)

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr.shape

(2, 4)

In [5]:
arr.size

8

In [6]:
arr

array([[ 11,  22,  33,  44],
       [ 22,  33,  55, 123]], dtype=int64)

In [7]:
#array which have zero elements
zeros=np.zeros((2,5))

In [8]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#range
rng=np.arange(15) #array of n-1 element
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
#linspace
lspace=np.linspace(1,5,12) # array of 12 element from 1 to 5
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [11]:
emp=np.empty((4,6)) #random element
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69119873e-306, 6.23057349e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60216183e-306,
        7.56602523e-307, 3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [12]:
print(type(rng))

<class 'numpy.ndarray'>


In [13]:
id=np.identity(10) #identity matrix

In [14]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
arr=np.arange(45)

In [18]:
arr.reshape(9,5) #reshaping the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [20]:
arr.ravel() #creates the 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [29]:
arr=arr.reshape(5,9)

In [31]:
arr.sum(axis=0) #sum of the elements of columns

array([ 90,  95, 100, 105, 110, 115, 120, 125, 130])

In [32]:
arr.sum(axis=1) #sum of rows

array([ 36, 117, 198, 279, 360])

In [35]:
arr=np.arange(9)
arr=arr.reshape(3,3)

In [36]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr.T #transpose the matrix

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [38]:
arr.flat #gives iterator

In [39]:
for i in arr.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [40]:
arr.ndim #gives number of dimension

2

In [48]:
arr.size #number of elements in array

9

In [49]:
arr.nbytes

36

In [54]:
one=np.array([1777,2,344,12])
print(one.argmax())  #index of maximum element
one.argmin()         #index of minimum element

2


0

In [58]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [60]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [61]:
arr1=np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
arr2=np.array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [63]:
arr1+arr2 #matrix addition

array([[ 0,  4,  8],
       [ 4,  8, 12],
       [ 8, 12, 16]])

In [64]:
arr1*arr2 #matrix mulitplication

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [66]:
np.where(arr1>1)

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [67]:
np.count_nonzero(arr1)

8

In [71]:
type(arr1.tolist())

list